version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    reviewers:
      - jamieastley
    assignees:
      - jamieastley
    schedule:
      interval: "daily"
      time: "19:00"
      timezone: "Australia/Sydney"

  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - jamieastley
    assignees:
      - jamieastley
    schedule:
      interval: "daily"
      time: "19:00"
      timezone: "Australia/Sydney"